#
#  mensabot
#
#  Copyright (c) 2010, Daniel Gasienica <daniel@gasienica.ch>
#  All rights reserved.
#

application: wilee-islab
version: 1
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: robot.py
- url: /web/.*
  script: robot.py
- url: /assets
  static_dir: assets
